services:
  backend:
    build: ./backend
    container_name: tripsparrow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/tripsparrow
      - ENVIRONMENT=development
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tripsparrow-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    container_name: tripsparrow-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripsparrow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: